src/config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks
  resources :units
  resources :landmarks
  resources :amenities

  devise_for :users, :path => '', :controllers => {registrations: 'users/registrations'},
             path_names: {sign_in: 'login', sign_up: 'sign_up', sign_out: 'logout', edit: 'profile'}

  get '/', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/search', to: 'static_pages#search'
  get '/search/:id', to: 'static_pages#single', as: 'search_single'
  # get '/single', to: 'static_pages#single'
  get '/faqs', to: 'static_pages#faqs'

  get '/users/:id', to: 'users#profile'


  get '/bookmarks', to: 'users#bookmarks'


  root 'static_pages#home'
end

src/app/models/amenity.rb
class Amenity < ApplicationRecord
end

src/app/controllers/amenities_controller.rb
class AmenitiesController < ApplicationController
  before_action :set_amenity, only: [:show, :edit, :update, :destroy]

  # GET /amenities
  # GET /amenities.json
  def index
    @amenities = Amenity.all
  end

  # GET /amenities/1
  # GET /amenities/1.json
  def show
  end

  # GET /amenities/new
  def new
    @amenity = Amenity.new
  end

  # GET /amenities/1/edit
  def edit
  end

  # POST /amenities
  # POST /amenities.json
  def create
    @amenity = Amenity.new(amenity_params)

    respond_to do |format|
      if @amenity.save
        format.html { redirect_to @amenity, notice: 'Amenity was successfully created.' }
        format.json { render :show, status: :created, location: @amenity }
      else
        format.html { render :new }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amenities/1
  # PATCH/PUT /amenities/1.json
  def update
    respond_to do |format|
      if @amenity.update(amenity_params)
        format.html { redirect_to @amenity, notice: 'Amenity was successfully updated.' }
        format.json { render :show, status: :ok, location: @amenity }
      else
        format.html { render :edit }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amenities/1
  # DELETE /amenities/1.json
  def destroy
    @amenity.destroy
    respond_to do |format|
      format.html { redirect_to amenities_url, notice: 'Amenity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amenity
      @amenity = Amenity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amenity_params
      params.require(:amenity).permit(:name, :description, :icon, :image_url)
    end
end

src/app/helpers/amenities_helper.rb
module AmenitiesHelper
end

src/app/views/amenities/_form.html.erb
<%= form_for(amenity) do |f| %>
  <% if amenity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amenity.errors.count, "error") %> prohibited this amenity from being saved:</h2>

      <ul>
      <% amenity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :icon %>
    <%= f.text_field :icon %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_area :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/amenities/edit.html.erb
<h1>Editing Amenity</h1>

<%= render 'form', amenity: @amenity %>

<%= link_to 'Show', @amenity %> |
<%= link_to 'Back', amenities_path %>

src/app/views/amenities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Amenities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Icon</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amenities.each do |amenity| %>
      <tr>
        <td><%= amenity.name %></td>
        <td><%= amenity.description %></td>
        <td><%= amenity.icon %></td>
        <td><%= amenity.image_url %></td>
        <td><%= link_to 'Show', amenity %></td>
        <td><%= link_to 'Edit', edit_amenity_path(amenity) %></td>
        <td><%= link_to 'Destroy', amenity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amenity', new_amenity_path %>

src/app/views/amenities/new.html.erb
<h1>New Amenity</h1>

<%= render 'form', amenity: @amenity %>

<%= link_to 'Back', amenities_path %>

src/app/views/amenities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @amenity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @amenity.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @amenity.icon %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @amenity.image_url %>
</p>

<%= link_to 'Edit', edit_amenity_path(@amenity) %> |
<%= link_to 'Back', amenities_path %>