src/config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks
  resources :units
  resources :landmarks
  resources :amenities

  devise_for :users, :path => '', :controllers => {registrations: 'users/registrations'},
             path_names: {sign_in: 'login', sign_up: 'sign_up', sign_out: 'logout', edit: 'profile'}

  get '/', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/search', to: 'static_pages#search'
  get '/search/:id', to: 'static_pages#single', as: 'search_single'
  # get '/single', to: 'static_pages#single'
  get '/faqs', to: 'static_pages#faqs'

  get '/users/:id', to: 'users#profile'


  get '/bookmarks', to: 'users#bookmarks'


  root 'static_pages#home'
end

src/app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :amenities
  has_and_belongs_to_many :landmarks
end

src/app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  layout 'flatfinder'
  # GET /units
  # GET /units.json

  def index
    @units = current_user.units # Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = current_user.units.where(id: params[:id]).first # Unit.all
    if (@unit.nil?)
      flash[:alert] = "The unit you are trying to access does not exist"
      redirect_to units_path
    end
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)
    @unit.user_id = current_user.id
    @unit.save

    respond_to do |format|
      if @unit.persisted?
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_unit
    @unit = current_user.units.where(id: params[:id]).first
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def unit_params
    params.require(:unit).permit(:status, :category, :name, :description, :size, :monthly_price, :weekly_price, :deposit_price, :city, :address, :min_capacity, :max_capacity, :showers, :sinks, :toilets, :urinals, :bathtubs, :kitchens, :bedrooms, :single_beds, :bunk_beds, :date_available, :min_weeks, :notes, :user_id)
  end
end

src/app/helpers/units_helper.rb
module UnitsHelper
end

src/app/views/units/_form.html.erb
<%= form_for(unit) do |f| %>
    <% if unit.errors.any? %>
        <div class="alert alert-dismissible alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h4>
          <ul>
            <% unit.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-lg-4">
        <div class="field form-group">
          <%= f.label :status %>
          <%= f.select :status, unit_statuses, {}, class: "form-control" %>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="field form-group">
          <%= f.label :category %>
          <%= f.select :category, unit_categories, {}, class: "form-control" %>
        </div>
      </div>
      <div class="col-lg-4">


        <div class="field form-group">
          <%= f.label :date_available %>
          <%= f.text_field :date_available, type: "date", class: "form-control"%>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="field form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="field form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control" %>
        </div>
        <div class="field form-group">
          <%= f.label :notes %>
          <%= f.text_area :notes, class: "form-control" %>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-lg-4">
        <div class="field form-group">
          <%= f.label :city %>
          <%= f.select :city, cities, {}, class: "form-control" %>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="field form-group">
          <%= f.label :address %>
          <%= f.text_area :address, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="field form-group">
          <%= f.label :size %>
          <div class="input-group">
            <%= f.number_field :size, class: "form-control", step: 0.5, min: 12 %>
            <span class="input-group-addon">square meters</span>
          </div>
        </div>
      </div>
      <div class="col-lg-4">

        <div class="field form-group">
          <%= f.label :min_weeks %>
          <%= f.number_field :min_weeks, class: "form-control", min: 1 %>
        </div>


      </div>
      <div class="col-lg-4">
        <div class="field form-group">
          <%= f.label :min_capacity %>
          <%= f.number_field :min_capacity, class: "form-control", min: 1 %>
        </div>
        <div class="field form-group">
          <%= f.label :max_capacity %>
          <%= f.number_field :max_capacity, class: "form-control", min: 1 %>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-lg-4">
        <div class="field form-group">
          <%= f.label :monthly_price %>
          <div class="input-group">
            <span class="input-group-addon">PHP</span>
            <%= f.number_field :monthly_price, class: "form-control", step: 0.5 %>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="field form-group">
          <%= f.label :weekly_price %>
          <div class="input-group">
            <span class="input-group-addon">PHP</span>
            <%= f.number_field :monthly_price, class: "form-control", step: 0.5 %>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="field form-group">
          <%= f.label :deposit_price %>
          <div class="input-group">
            <span class="input-group-addon">PHP</span>
            <%= f.number_field :monthly_price, class: "form-control", step: 0.5 %>
          </div>
        </div>
      </div>
    </div>






    <div class="row">

      <div class="col-lg-4">
        <div class="field form-group">
          <%= f.label :kitchens %>
          <%= f.number_field :kitchens, class: "form-control", min: 1 %>
        </div>

        <div class="field form-group">
          <%= f.label :bedrooms %>
          <%= f.number_field :bedrooms, class: "form-control", min: 1 %>
        </div>

      </div>
      <div class="col-lg-4">

        <div class="field form-group">
          <%= f.label :single_beds %>
          <%= f.number_field :single_beds, class: "form-control", min: 1 %>
        </div>

        <div class="field form-group">
          <%= f.label :bunk_beds %>
          <%= f.number_field :bunk_beds, class: "form-control", min: 1 %>
        </div>

      </div>
      <div class="col-lg-4">

        <div class="field form-group">
          <%= f.label :showers %>
          <%= f.number_field :showers, class: "form-control", min: 1 %>
        </div>

        <div class="field form-group">
          <%= f.label :sinks %>
          <%= f.number_field :sinks, class: "form-control", min: 1 %>
        </div>

        <div class="field form-group">
          <%= f.label :toilets %>
          <%= f.number_field :toilets, class: "form-control", min: 1 %>
        </div>

        <div class="field form-group">
          <%= f.label :urinals %>
          <%= f.number_field :urinals, class: "form-control", min: 1 %>
        </div>

        <div class="field form-group">
          <%= f.label :bathtubs %>
          <%= f.number_field :bathtubs, class: "form-control", min: 1 %>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-lg-4"></div>
      <div class="col-lg-4"></div>
      <div class="col-lg-4">

        <div class="actions">
          <%= f.submit class: "btn btn-primary btn-block" %>
        </div>
      </div>
    </div>



<% end %>

src/app/views/units/edit.html.erb
<header class="intro-header">
  <div class="container">
    <div class="site-heading">
      <h1>
        <span class="c-b3">Edit</span>
        <span class="c-b1">Unit</span>
      </h1>
      <hr class="small">
      <span class="subheading">This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit ...</span>
    </div>
  </div>
</header>
<hr>
<br>

<%= render 'form', unit: @unit %>
<hr>
<div class="row">
  <div class="col-lg-4"></div>
  <div class="col-lg-4">
    <%= link_to 'Show', @unit, class: "btn btn-warning btn-block" %>
  </div>
  <div class="col-lg-4">
    <%= link_to 'Back', units_path, class: "btn btn-default btn-block" %>
  </div>
</div>

src/app/views/units/index.html.erb
<header class="intro-header">
  <div class="container">
    <div class="site-heading">
      <h1>
        <span class="c-b3">My</span>
        <span class="c-b1">Units</span>
      </h1>
      <hr class="small">
      <span class="subheading">This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit ...</span>
    </div>
  </div>
</header>
<hr>
<br>
<div class="" id="units">
  <div class="input-group">
    <input type="text" class="search form-control" placeholder="Search for...">
    <span class="input-group-btn">
      <button class="btn btn-default sort" type="button" data-sort="unit-name">name <i class="fa fa-sort"></i></button>
        <button class="btn btn-default sort" type="button" data-sort="unit-price">price <i class="fa fa-sort"></i> </button>
        <button class="btn btn-default sort" type="button" data-sort="unit-location">location <i class="fa fa-sort"></i></button>
        <%= link_to 'New Unit', new_unit_path, class: "btn btn-success" %>
      </span>
  </div>
  <br>
  <div class="row list">


    <% @units.each do |unit| %>
        <div class="col-sm-4 col-lg-4 col-md-4">
          <div class="thumbnail">
            <a href="<%= unit_url(unit) %>" style="cursor: pointer">
              <img class="slide-image" src="http://placehold.it/320x180" alt="">
            </a>
            <div class="text-center">
              <small class="">
                <strong>
                  <a href="<%= unit %>" class="unit-name"><%= unit.name %> </a>
                </strong>
                <p><%= unit.description %></p>
              </small>
            </div>
            <div class="text-center">
              <div class="btn btn-group btn-group-justified btn-group" style="margin: 0px; padding: 0px">
                <a href="#" class="btn btn-clear unit-location">
                  <%= unit.city.upcase %>

                </a>

                <a href="#" class="btn btn-clear" style="">
                  <%= unit.category %> <br>
                </a>
                <a href="#" class="btn btn-clear">
                  <%= unit.size %> m²
                </a>
              </div>
              <div class="btn btn-group btn-group-justified btn-group" style="margin: 0px; padding: 0px">
                <a href="#" class="btn btn-clear unit-filled">
                  <%= unit.min_capacity %> - <%= unit.max_capacity %>
                  <br> TENANTS
                </a>
                <a href="#" class="btn btn-clear unit-price">
                  PHP <%= unit.monthly_price %> <br/>MONTH
                </a>

              </div>
            </div>
            <div class="btn btn-group btn-group-justified" style="margin: 0px; padding: 0px">
              <%= link_to 'Show', unit, class: "btn btn-default" %>
              <%= link_to 'Edit', edit_unit_path(unit), class: "btn btn-warning" %>
              <%= link_to 'Destroy', unit, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
            </div>
          </div>

        </div>
        </div>
    <% end %>
    </div>
</div>

src/app/views/units/index_old.html.erb
<header class="intro-header">
  <div class="container">
    <div class="site-heading">
      <h1>
        <span class="c-b3">My</span>
        <span class="c-b1">Units</span>
      </h1>
      <hr class="small">
      <span class="subheading">This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit ...</span>
    </div>
  </div>
</header>
<hr>
<br>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Status</th>
    <th>Category</th>
    <th>Name</th>
    <th>Description</th>
    <th>Size</th>
    <!--<th>Monthly price</th>-->
    <!--<th>Weekly price</th>-->
    <!--<th>Deposit price</th>-->
    <!--<th>City</th>-->
    <!--<th>Address</th>-->
    <!--<th>Min capacity</th>-->
    <!--<th>Max capacity</th>-->
    <!--<th>Showers</th>-->
    <!--<th>Sinks</th>-->
    <!--<th>Toilets</th>-->
    <!--<th>Urinals</th>-->
    <!--<th>Bathtubs</th>-->
    <!--<th>Kitchens</th>-->
    <!--<th>Bedrooms</th>-->
    <!--<th>Single beds</th>-->
    <!--<th>Bunk beds</th>-->
    <!--<th>Date available</th>-->
    <th>Min weeks</th>
    <th>Notes</th>
    <!--<th>User</th>-->
    <th colspan="3" width="10%">
      <%= link_to 'New Unit', new_unit_path, class: "btn btn-success btn-block" %>
    </th>
  </tr>
  </thead>

  <tbody>
  <% @units.each do |unit| %>
      <tr>
        <td><%= unit.status %></td>
        <td><%= unit.category %></td>
        <td><%= unit.name %></td>
        <td><%= unit.description %></td>
        <!--<td><%= unit.size %></td>-->
        <!--<td><%= unit.monthly_price %></td>-->
        <!--<td><%= unit.weekly_price %></td>-->
        <!--<td><%= unit.deposit_price %></td>-->
        <!--<td><%= unit.city %></td>-->
        <!--<td><%= unit.address %></td>-->
        <!--<td><%= unit.min_capacity %></td>-->
        <!--<td><%= unit.max_capacity %></td>-->
        <!--<td><%= unit.showers %></td>-->
        <!--<td><%= unit.sinks %></td>-->
        <!--<td><%= unit.toilets %></td>-->
        <!--<td><%= unit.urinals %></td>-->
        <!--<td><%= unit.bathtubs %></td>-->
        <!--<td><%= unit.kitchens %></td>-->
        <!--<td><%= unit.bedrooms %></td>-->
        <!--<td><%= unit.single_beds %></td>-->
        <!--<td><%= unit.bunk_beds %></td>-->
        <td><%= unit.date_available %></td>
        <td><%= unit.min_weeks %></td>
        <td><%= unit.notes %></td>
        <!--<td><%= unit.user %></td>-->
        <td><%= link_to 'Show', unit, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>

src/app/views/units/new.html.erb
<header class="intro-header">
  <div class="container">
    <div class="site-heading">
      <h1>
        <span class="c-b3">New</span>
        <span class="c-b1">Unit</span>
      </h1>
      <hr class="small">
      <span class="subheading">This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit ...</span>
    </div>
  </div>
</header>
<hr>
<br>


<%= render 'form', unit: @unit %>
<hr>
<div class="row">
  <div class="col-lg-4"></div>
  <div class="col-lg-4">
  </div>
  <div class="col-lg-4">
    <%= link_to 'Back', units_path, class:"btn btn-default btn-block" %>
  </div>
</div>

src/app/views/units/show.html.erb
<header class="intro-header">
  <div class="container">
    <div class="site-heading">
      <h1>
        <span class="c-b1"> <%= @unit.name.capitalize %></span>
      </h1>
      <hr class="small">
      <span class="subheading"><%= @unit.description.capitalize %> ...</span>
    </div>
  </div>
</header>
<hr>
<br>

<p>
  <strong>Status:</strong>
  <%= @unit.status %>
</p>

<p>
  <strong>Category:</strong>
  <%= @unit.category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @unit.description %>
</p>

<p>
  <strong>Size:</strong>
  <%= @unit.size %>
</p>

<p>
  <strong>Monthly price:</strong>
  <%= @unit.monthly_price %>
</p>

<p>
  <strong>Weekly price:</strong>
  <%= @unit.weekly_price %>
</p>

<p>
  <strong>Deposit price:</strong>
  <%= @unit.deposit_price %>
</p>

<p>
  <strong>City:</strong>
  <%= @unit.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @unit.address %>
</p>

<p>
  <strong>Min capacity:</strong>
  <%= @unit.min_capacity %>
</p>

<p>
  <strong>Max capacity:</strong>
  <%= @unit.max_capacity %>
</p>

<p>
  <strong>Showers:</strong>
  <%= @unit.showers %>
</p>

<p>
  <strong>Sinks:</strong>
  <%= @unit.sinks %>
</p>

<p>
  <strong>Toilets:</strong>
  <%= @unit.toilets %>
</p>

<p>
  <strong>Urinals:</strong>
  <%= @unit.urinals %>
</p>

<p>
  <strong>Bathtubs:</strong>
  <%= @unit.bathtubs %>
</p>

<p>
  <strong>Kitchens:</strong>
  <%= @unit.kitchens %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @unit.bedrooms %>
</p>

<p>
  <strong>Single beds:</strong>
  <%= @unit.single_beds %>
</p>

<p>
  <strong>Bunk beds:</strong>
  <%= @unit.bunk_beds %>
</p>

<p>
  <strong>Date available:</strong>
  <%= @unit.date_available %>
</p>

<p>
  <strong>Min weeks:</strong>
  <%= @unit.min_weeks %>
</p>

<p>
  <strong>Notest:</strong>
  <%= @unit.notes %>
</p>
<hr>
<div class="row">
  <div class="col-lg-4"></div>
  <div class="col-lg-4">
    <%= link_to 'Edit', edit_unit_path(@unit), class: "btn btn-warning btn-block" %>
  </div>
  <div class="col-lg-4">
    <%= link_to 'Back', units_path, class: "btn btn-default btn-block" %>
  </div>
</div>