src/config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks
  resources :units
  resources :landmarks
  resources :amenities

  devise_for :users, :path => '', :controllers => {registrations: 'users/registrations'},
             path_names: {sign_in: 'login', sign_up: 'sign_up', sign_out: 'logout', edit: 'profile'}

  get '/', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/search', to: 'static_pages#search'
  get '/search/:id', to: 'static_pages#single', as: 'search_single'
  # get '/single', to: 'static_pages#single'
  get '/faqs', to: 'static_pages#faqs'

  get '/users/:id', to: 'users#profile'


  get '/bookmarks', to: 'users#bookmarks'


  root 'static_pages#home'
end

src/app/models/landmark.rb
class Landmark < ApplicationRecord
end

src/app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  before_action :set_landmark, only: [:show, :edit, :update, :destroy]

  # GET /landmarks
  # GET /landmarks.json
  def index
    @landmarks = Landmark.all
  end

  # GET /landmarks/1
  # GET /landmarks/1.json
  def show
  end

  # GET /landmarks/new
  def new
    @landmark = Landmark.new
  end

  # GET /landmarks/1/edit
  def edit
  end

  # POST /landmarks
  # POST /landmarks.json
  def create
    @landmark = Landmark.new(landmark_params)

    respond_to do |format|
      if @landmark.save
        format.html { redirect_to @landmark, notice: 'Landmark was successfully created.' }
        format.json { render :show, status: :created, location: @landmark }
      else
        format.html { render :new }
        format.json { render json: @landmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landmarks/1
  # PATCH/PUT /landmarks/1.json
  def update
    respond_to do |format|
      if @landmark.update(landmark_params)
        format.html { redirect_to @landmark, notice: 'Landmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @landmark }
      else
        format.html { render :edit }
        format.json { render json: @landmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landmarks/1
  # DELETE /landmarks/1.json
  def destroy
    @landmark.destroy
    respond_to do |format|
      format.html { redirect_to landmarks_url, notice: 'Landmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landmark
      @landmark = Landmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landmark_params
      params.require(:landmark).permit(:name, :description, :icon, :image_url)
    end
end

src/app/helpers/landmarks_helper.rb
module LandmarksHelper
end

src/app/views/landmarks/_form.html.erb
<%= form_for(landmark) do |f| %>
  <% if landmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(landmark.errors.count, "error") %> prohibited this landmark from being saved:</h2>

      <ul>
      <% landmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :icon %>
    <%= f.text_field :icon %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_area :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/landmarks/edit.html.erb
<h1>Editing Landmark</h1>

<%= render 'form', landmark: @landmark %>

<%= link_to 'Show', @landmark %> |
<%= link_to 'Back', landmarks_path %>

src/app/views/landmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Landmarks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Icon</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @landmarks.each do |landmark| %>
      <tr>
        <td><%= landmark.name %></td>
        <td><%= landmark.description %></td>
        <td><%= landmark.icon %></td>
        <td><%= landmark.image_url %></td>
        <td><%= link_to 'Show', landmark %></td>
        <td><%= link_to 'Edit', edit_landmark_path(landmark) %></td>
        <td><%= link_to 'Destroy', landmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Landmark', new_landmark_path %>

src/app/views/landmarks/new.html.erb
<h1>New Landmark</h1>

<%= render 'form', landmark: @landmark %>

<%= link_to 'Back', landmarks_path %>

src/app/views/landmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @landmark.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @landmark.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @landmark.icon %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @landmark.image_url %>
</p>

<%= link_to 'Edit', edit_landmark_path(@landmark) %> |
<%= link_to 'Back', landmarks_path %>