src/config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks
  resources :units
  resources :landmarks
  resources :amenities

  devise_for :users, :path => '', :controllers => {registrations: 'users/registrations'},
             path_names: {sign_in: 'login', sign_up: 'sign_up', sign_out: 'logout', edit: 'profile'}

  get '/', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/search', to: 'static_pages#search'
  get '/search/:id', to: 'static_pages#single', as: 'search_single'
  # get '/single', to: 'static_pages#single'
  get '/faqs', to: 'static_pages#faqs'

  get '/users/:id', to: 'users#profile'


  get '/bookmarks', to: 'users#bookmarks'


  root 'static_pages#home'
end

src/app/views/shared/_footer.html.erb
<footer class="">
  <div class="container">
    <hr/>
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center">
          <li>
            <a href="#" data-toggle="tooltip" title="@FlatFinderPH">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="https://www.facebook.com/flatfinder.ph" target="_blank" data-toggle="tooltip" title="fb.com/flatfinder.ph">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="#" data-toggle="tooltip" title="@FlatFinderPH">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="mailto:flatfinder.ph@gmail.com?subject=FlatFinder" target="_blank" data-toggle="tooltip" title="flatfinder.ph@gmail.com">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-envelope-o fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="#" data-toggle="tooltip" title="+63 916 214 442 5">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-mobile-phone fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <hr/>
    <div class="row">
      <div class="col-lg-8">
        <h3 class="centered">FIND US</h3>
        <div  style="height: 14em;" class="border">
          <div id="map-container-footer" style="height: 100%; width: 100%">
          </div>
        </div>
        <br>
      </div>
      <div class="col-lg-4">
        <h3 class="centered">SEND US A MESSAGE</h3>
        <form class="form-horizontal" role="form">
          <div class="form-group">
            <label for="inputEmail1" class="col-lg-4 control-label"></label>
            <div class="col-lg-10">
              <input type="email" class="form-control" id="inputEmail1" placeholder="Email">
            </div>
          </div>
          <div class="form-group">
            <label for="text1" class="col-lg-4 control-label"></label>
            <div class="col-lg-10">
              <input type="text" class="form-control" id="text1" placeholder="Your Name">
            </div>
          </div>
          <div class="form-group">
            <label for="mobile" class="col-lg-4 control-label"></label>
            <div class="col-lg-10">
              <input type="text" class="form-control" id="text1" placeholder="Mobile Number">
            </div>
          </div>
          <div class="form-group">
            <label for="message-box" class="col-lg-4 control-label"></label>
            <div class="col-lg-10">
              <input type="text" class="form-control" id="text1" placeholder="Message">
            </div>
          </div>
          <div class="form-group">
            <div class="col-lg-10">
              <button type="submit" class="btn btn-danger pull-right">
                Submit
                <i class="fa fa-envelope-o"></i>
              </button>
            </div>
          </div>
        </form><!-- form -->
      </div><!-- col FORM -->

    </div>
  </div>
  <div class="container">
    <hr/>
    <p class="text-center">Copyright &copy; FlatFinder.com 2016</p>
  </div>
</footer>

src/app/views/shared/_header.html.erb
<header class="intro-header" style="">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <img src="<%= "/icon.png" %>" width="128" alt="" class="img img-responsive center-block">
          <hr class="small">
          <h1>
            <span class="c-b3">Flat</span><span class="c-b1">Finder</span>
          </h1>

          <span class="subheading">Your next place is just a few clicks away</span>
        </div>
      </div>
    </div>
  </div>
</header>
<hr>
<br/>

src/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        Menu <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand" href="<%= root_url %>#">
        <img src="<%= "/icon_navbar.png" %>" alt="" class="" style="height: 1.5em; display: inline; ">
        <span class="c-b3">Flat</span><span class="c-b1">Finder</span>
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="<%= root_url %>#">Home</a>
        </li>
        <li>
          <a href="<%= search_url %>">Search</a>
        </li>
        <li>
          <a href="<%= about_url %>">About</a>
        </li>
        <li>
          <a href="<%= faqs_url %>">Faqs</a>
        </li>

        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <%= current_user.email %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<%= edit_user_registration_url %>">Manage Account</a></li>
                <li class="divider"></li>
                <!--<li><a href="#">Reservations</a></li>-->
                <!--<li><a href="#">Payments</a></li>-->
                <li><a href="<%= bookmarks_url %>">Bookmarks</a></li>
                <li><a href="<%= units_path %>">Units</a></li>
                <li class="divider"></li>
                <li>
                  <%= link_to('Logout', destroy_user_session_url, :method => :delete) %>
                </li>
              </ul>
            </li>

        <% else %>
            <li>
              <a href="<%= new_user_session_url %>">Login</a>
            </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>